name: Production

on:
  pull_request:
    types:
      - closed

jobs:
  production_deployment:
    runs-on: ubuntu-20.04
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: 'srv-clb7icaqviqc73cluu1g'
          api-key: ${{ secrets.RENDER_TOKEN }}
